name: Run update.py and commit changes

on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * *"  # every day at 01:00 UTC

permissions:
  contents: write

jobs:
  run-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update.py
        timeout-minutes: 30
        run: |
          python update.py

      - name: Commit and push changes (if any)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: run update.py [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
